#!/bin/bash
# execute without installing

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export PYTHONPATH=$PYTHONPATH:$DIR:$DIR/docker_push_ssh
exec python -m docker_push_ssh.cli $@
